CheckOut/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth

app_name = "checkout"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("user.urls")),
    path(
        "logout/",
        auth.LogoutView.as_view(template_name="user/index.html"),
        name="logout",
    ),
    path("libraries/", include("libraries.urls")),
    path("bookclub/", include("BookClub.urls")),
    path("notifications/", include("Notifications.urls")),
    path("books/", include("books.urls")),
    path("chat/", include("chat.urls")),
]

Notifications/urls.py
from django.urls import path
from Notifications.views import NotificationListView

app_name = "notifications"

urlpatterns = [path("", NotificationListView.as_view(), name="notifications")]

chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
    path("name/<str:roomname>/", views.name, name="name"),
]

libraries/urls.py
from django.urls import path
from libraries.views import LibraryView, LibraryListView

app_name = "libraries"
urlpatterns = [
    path("<int:pk>", LibraryView.as_view(), name="library-detail"),
    path("", LibraryListView.as_view(), name="library-list"),
]

login/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.login, name="login"),
]

user/urls.py
from django.urls import path, reverse_lazy
from . import views
from .views import ChangePasswordView, ResetPasswordView
from django.contrib.auth import views as auth_views

app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.user_login, name="login"),
    path("register", views.register, name="register"),
    path("profile", views.user_profile, name="user_profile"),
    path("unsubscribe/<slug:slug>/", views.unsubscribe, name="unsubscribe"),
    path("mute/<slug:slug>/", views.mute, name="mute"),
    path("password-change/", ChangePasswordView.as_view(), name="password_change"),
    path(
        "password-reset/",
        ResetPasswordView.as_view(),
        {
            "post_reset_redirect": "users:password_reset_complete",
        },
        name="password-reset",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="user/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="user/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

CheckOut/login/models.py
from django.db import models

# Create your models here.

CheckOut/user/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# class UserProfile(models.Model):

#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     bio = models.TextField()

#     def __str__(self):
#         return self.user.username

#     def get_absolute_url(self):
#         return reverse("_detail", kwargs={"pk": self.pk})

user/models.py
import re
from django.db import models
from django.contrib.auth.models import AbstractUser
from Notifications.models import Notification
from django.db.models import Q


class CustomUser(AbstractUser):
    STATUS = (
        ("reader", "Reader"),
        ("librarian", "Librarian"),
        ("nyu", "NYU Associated"),
    )

    username = models.CharField(max_length=50, blank=True, null=True, unique=True)
    email = models.EmailField(max_length=254, unique=True)
    first_name = models.CharField(max_length=50, blank=True, null=True, unique=False)
    last_name = models.CharField(max_length=50, blank=True, null=True, unique=False)
    status = models.CharField(max_length=100, choices=STATUS, default="reader")

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = [
        "email",
    ]

    def get_unread_notifications(self):
        unread_notifications = Notification.objects.filter(
            Q(
                transferownershipnotif__new_owner=self.id,
                transferownershipnotif__status="pending",
                is_read=False,
            )
            | Q(
                transferownershipnotif__original_owner=self.id,
                transferownershipnotif__status="declined",
                is_read=False,
            )
            | Q(bookclubupdatesnotif__receiving_user=self.id, is_read=False)
        ).count()

        return unread_notifications

    def get_user_status(email):
        domain = re.search(r"@[\w.]+", email).group()
        if domain == "@nyu.edu":
            return "nyu"
        else:
            return "reader"

    def save(self, *args, **kwargs):
        self.status = CustomUser.get_user_status(self.email)
        super(CustomUser, self).save(*args, **kwargs)

    def __str__(self):
        return self.username

CheckOut/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import validate_email
from django.core.validators import RegexValidator
# from .models import UserProfile

class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={'placeholder': 'First Name','class': 'form-control'}))
    last_name = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={'placeholder': 'Last Name','class': 'form-control'}))
    username = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={'placeholder': 'Username','class': 'form-control'}))
    email = forms.EmailField(required=True, label='Email', widget=forms.TextInput(attrs={'placeholder': 'email','class': 'form-control'}))
    password1 = forms.CharField(max_length=20, required=True, label='Password', widget=forms.PasswordInput(attrs={'placeholder': 'Password','class': 'form-control'}))
    password2 = forms.CharField(max_length=20, required=True, label='Confirm Password', widget=forms.PasswordInput(attrs={'placeholder': 'Re-enter Password','class': 'form-control'}))
    
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']
    
    def clean_email(self):  
        email = self.cleaned_data['email'].lower()  
        new = User.objects.filter(email=email)  
        #if new.count():
        #    raise forms.ValidationError("Email Already Exist")  
        #if not validate_email(email):
        #    raise forms.ValidationError("Incorrect email format!") 
        return email  
        
    def clean_password1(self):
        password = self.cleaned_data.get("password1")
        if password.isnumeric():
            raise forms.ValidationError("Password cannot only contain numbers")
        elif password.isalpha():
            raise forms.ValidationError("Password cannot only contain characters")
        else:
            return password

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(required=True) # TODO: send confirmation email to change?

    class Meta:
        model = User
        fields = ['username', 'email']			

class ValidateForm(forms.Form):
	alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')
	code = forms.CharField(max_length=10, validators=[alphanumeric])
	
	def clean_code(self):
		code = self.cleaned_data.get('code')
		if code.isalnum():
			return code
		raise forms.ValidationError("Code can only be alphanumeric")

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator
from validate_email import validate_email
from .models import CustomUser


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "First Name", "class": "form-control"}
        ),
    )
    last_name = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Last Name", "class": "form-control"}
        ),
    )
    username = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Username", "class": "form-control"}
        ),
    )
    email = forms.EmailField(
        required=True,
        label="Email",
        widget=forms.TextInput(attrs={"placeholder": "email", "class": "form-control"}),
    )
    password1 = forms.CharField(
        max_length=20,
        required=True,
        label="Password",
        widget=forms.PasswordInput(
            attrs={"placeholder": "Password", "class": "form-control"}
        ),
    )
    password2 = forms.CharField(
        max_length=20,
        required=True,
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={"placeholder": "Re-enter Password", "class": "form-control"}
        ),
    )

    class Meta:
        model = CustomUser
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
        ]

    def clean_email(self):
        email = self.cleaned_data["email"].lower()
        new = CustomUser.objects.filter(email=email)
        if new.count():
            raise forms.ValidationError(
                "Email already exists! Please use another email."
            )
        is_valid = validate_email(email)
        if not is_valid:
            raise forms.ValidationError("Incorrect email format!")
        return email

    def clean_password1(self):
        password = self.cleaned_data.get("password1")
        if password.isnumeric():
            raise forms.ValidationError("Password cannot only contain numbers")
        elif password.isalpha():
            raise forms.ValidationError("Password cannot only contain characters")
        else:
            return password


class UpdateUserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UpdateUserForm, self).__init__(*args, **kwargs)
        try:
            self.fields["email"].initial = self.instance.email
        except CustomUser.DoesNotExist:
            pass

    username = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Username", "class": "form-control"}
        ),
    )

    first_name = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "First Name", "class": "form-control"}
        ),
    )
    last_name = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Last Name", "class": "form-control"}
        ),
    )

    email = forms.EmailField(
        required=True,
        label="Email",
        widget=forms.TextInput(attrs={"placeholder": "email", "class": "form-control"}),
    )

    class Meta:
        model = CustomUser
        fields = ["username", "first_name", "last_name", "email"]

    def clean_email(self):
        email = self.cleaned_data["email"].lower()
        new = CustomUser.objects.filter(email=email)
        if email != self.instance.email and new.count():
            raise forms.ValidationError(
                "Email already exists! Please use another email."
            )
        is_valid = validate_email(email)
        if not is_valid:
            raise forms.ValidationError("Incorrect email format!")
        return email


class ValidateForm(forms.Form):
    alphanumeric = RegexValidator(
        r"^[0-9a-zA-Z]*$", "Only alphanumeric characters are allowed."
    )
    code = forms.CharField(max_length=10, validators=[alphanumeric])

    def clean_code(self):
        code = self.cleaned_data.get("code")
        if code.isalnum():
            return code
        raise forms.ValidationError("Code can only be alphanumeric")

CheckOut/login/views.py
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.template import loader

# Create your views here.


def login(request):
	template = loader.get_template('login/login.html')
	context = {}
	return HttpResponse(template.render(context, request))
    
	

CheckOut/user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from .forms import UserRegisterForm, ValidateForm
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
from django.urls import reverse_lazy
from smtplib import SMTP, SMTPException
import time
import random,string

from .forms import UserRegisterForm, UpdateUserForm
from django.views import View

    
def index(request):
	return render(request, 'user/index.html', {'title':'index'})

def register(request):
	if request.method == 'POST':
		if 'signup' in request.POST:
			form = UserRegisterForm(request.POST)
			request.session['register_form'] = request.POST
			if form.is_valid():
				vcode = ''.join(random.choices(string.ascii_letters, k=5))
				email = form.cleaned_data.get('email');
				print(f'vcode: {vcode}')
				request.session['verification_code'] = { 'code': vcode , 'ttl' : (time.time() + 300)}
				subject, from_email,message = 'Verify Your Email', 'test@gmail.com', f'This is your verification code: {vcode}'
				try:
					send_mail(subject,message,from_email,[email],fail_silently = False,)
					context = {
						'form' : form,
						'title' : 'validate code',
						'verify_code': True,
					}
					return render(request,'user/register.html',context)
				except SMTPException as e:
					print(e)
					context = {
						'form' : form,
						'title' : 'validate code',
						'verify_code': True,
						'email_send_failed' : True
					}
					return render(request,'user/register.html',context)
		elif 'verify' in request.POST:
			print('Verify stuff')
			validate_form = ValidateForm(request.POST)
			print(request.POST)
			if validate_form.is_valid():
				code = validate_form.cleaned_data.get('code')
				validation_token = request.session.get('verification_code')
				print(f'{validation_token}\n Time Now: {time.time()}')
				if validation_token and validation_token['ttl'] > time.time():
					if code == validation_token['code'] :
						post_req = request.session.pop('register_form')
						form = UserRegisterForm(post_req)
						form.save()
						username = form.cleaned_data.get('username')
						email = form.cleaned_data.get('email')
						password = form.cleaned_data.get('password1')
							
						user = authenticate(username=username,password=password)
						login(request,user)
						messages.success(request, f'Your account has been created ! You are now able to log in')
						del request.session['verification_code']
						return redirect('users:index')
					else:
						context = {
							'title' : 'validate code',
							'verify_code': True,
							'validate_failed': True,
							'error_text': 'Incorrect Validation Code, make sure you entered in the right code.'
						}
						return render(request,'user/register.html',context)
				else:
					context = {
							'title' : 'validate code',
							'verify_code': True,
							'validate_failed': True,
							'error_text': 'The verification code has expired.'
					}
					return render(request,'user/register.html',context)
			else:
				print("Failed validation")
			
	else:
		form = UserRegisterForm()
	return render(request, 'user/register.html', {'form': form, 'title':'register here'})

def Login(request):
	if request.method == 'POST':

		# TODO: use AuthenticationForm

		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username = username, password = password)
		if user is not None:
			form = login(request, user)
			messages.success(request, f' welcome {user.username} !!')
			return redirect('users:index')
		else:
			messages.info(request, f'account does not exist plz sign in')
	form = AuthenticationForm()
	return render(request, 'user/login.html', {'form':form, 'title':'log in'})

@login_required
def user_profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users:user_profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        
    return render(request, 'user/profile.html', {'user_form': user_form})

class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'user/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('users:index')

login/views.py
from django.http import HttpResponse
from django.template import loader

# Create your views here.


def login(request):
    template = loader.get_template("login/login.html")
    context = {}
    return HttpResponse(template.render(context, request))

user/templates/user/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %} {% load bootstrap_icons %}
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <title>{% block title %}Check Out{% endblock %}</title>
</head>
<style>
    @media (min-width: 979px) {
        #content {
        padding-top: 0px;
      }
    }
    #content {
      padding-top: 60px;
    }
</style> 
<body>
    {% block navbar %}
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg fixed-top" style="font-size: small">
        <div class="container-fluid">
            <a class="navbar-brand" style="font-size: medium" href="{% url "users:index" %}">Check Out</a>
            <div class="collapse navbar-collapse" id="mainNavBar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                    <a class="nav-link active" href="{% url "users:index" %}">{% bs_icon 'house-door' %}Home</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        <li>
                            <a class="nav-link active" href="{% url "notifications:notifications" %}">{% bs_icon 'bell' %}
                                {% if user.get_unread_notifications %}
                                <span class="rounded-circle" style="position: absolute;
                                top: 25 px;
                                right: 120 px;
                                padding: 5px 5px;
                                border-radius: 50%;
                                background: red;
                                color: white;
                                ">
                                    <span class="visually-hidden">New alerts</span>
                                </span>
                                {% endif %}
                            </a>
                        </li class="nav-item">
                        <li>
                            <a class="nav-link active" href="{% url "users:user_profile" %}">{% bs_icon 'person-gear' %}User Profile</a>
                        </li class="nav-item">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url "logout" %}">{% bs_icon 'box-arrow-left' %}Logout</a></li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url "users:register" %}">{% bs_icon 'person' %}Sign up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url "users:login" %}">{% bs_icon 'box-arrow-right' %}Log in</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% endblock %}
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

user/templates/user/index.html
{% extends "user/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="title" content="project">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="language" content="English">

<title>{{title}}</title>
<!-- bootstrap file -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- bootstrap file-->

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<!-- main css -->
<link rel="stylesheet" type="text/css" href="{% static "index.css" %}" />


<!-- message here -->


</head>
{% block content %}
<body>

{% include "user/base.html" %}
<div class="container-fluid">
<div class="row">
	{% block start %}
	{% if user.is_authenticated %}
		<div class="container">
			<center><h3>Welcome back {{user.first_name}}!</h3></center>
		{% else %}
			<center><h3>Check Out</h3></center>
		{% endif %}
			</br>
		</div>
</div>
</div>
		<div class="container d-flex justify-content-md-center">
				<form id="searchForm" class="row" action="{% url 'libraries:library-list' %}">
					{% csrf_token%}
					<div class="col-md-11">
						<input class="form-control" id="searchInput" class="form-control" type="search" placeholder="Search or view all libraries" aria-label="Search" name="search" value="{{ search_value }}">
					</div>	
					<div class="col-md-1">
						<button class="btn btn-dark" type="submit">Search</button>
					</div>	
				</form>
		</div>
		</br>
	{% endblock %}
	<div class="container-fluid">
	<div class="row">
	{% if user.is_authenticated and isfrontpage %}
	{% block subscriptions %}
		<div class="container">
			<div class="row">
				<div class='col-2'></div>
				<div class="col-8">
					{% if messages %}
						{% for message in messages %}
						<div class="container-fluid p-0">
						<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
							{{ message }}
							<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
						</div>
						</div>
						{% endfor %}
					{% endif %}

					{% if subscriptions %}
						<center><h4>Your Subscriptions</h4></center>
					{% else %}
						<center>Looks like your not subscribed to any book clubs.</center>
					{% endif %}
					{% for club in subscriptions %}
						<div class='card' style="width: 100%;margin-bottom:10px;">
							<div class="card-body">
								<div class="card-title">
									<div class='row'>
										<div class='col-6'>
											{% if club.admin == request.user %}
												<p style="font-size:16px"><span class="text-primary">OWNER</span> | <a href="{% url 'details' club.id %}"> <b>{{club.name}}</b></a></p>
											{% else %}
												<p style="font-size:16px"><span class="text-primary">MEMBER</span> | <a href="{% url 'details' club.id %}"><b>{{club.name}}</b></a></p>
											{% endif %}
											
										</div>
										<div class='col-6' style='float: right;'>
											<div style='float:right'>
												{% if club.admin == request.user %}
													<div style='float:left;margin:2px'>
													<a href="{% url 'edit_book_club' club.id %}" class="btn btn-primary" style="font-size:14px">Edit</a>
													</div>
												{% endif %}
												<form style='float:left;margin:2px' method="POST" action="{% url 'users:unsubscribe' club.id %}">
													{% csrf_token %}
													<button type="submit" class="btn btn-warning" style="font-size:14px">Unsubscribe</button>
												</form>
												{% if request.user in club.silenceNotification.all %}
													<form style='float:left;margin:2px' method="POST" action="{% url 'users:mute' club.id %}">
														{% csrf_token %}
														<button type="submit" name="unmute" class="btn btn-secondary" style="font-size:14px">Unmute</button>
													</form>
												{% else %}
													<form style='float:left;margin:2px' method="POST" action="{% url 'users:mute' club.id %}">
														{% csrf_token %}
														<button type="submit" name="mute" class="btn btn-secondary" style="font-size:14px">Mute</button>
													</form>
												{% endif %}
											</div>
											
										</div>
									</div>
								</div>
								<div class="card-text">
									<b style="font-size:16px">{{club.libraryId.branch}}</b><br>
									Meeting Day: {{club.meetingDay}}<br>
									Current Book: {{club.currentBook}}<br>
									Description: {{club.description}}
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
				<div class='col-2'></div>
			</div>
		</div>
	{% endblock %}
	{% endif %}
	{% if not user.is_authenticated and isfrontpage %}
		<center>Login for to view subscriptions</center>
	{% endif %}
</div>
</div>
</div>
</body>
{% endblock %}
</html>

user/templates/user/login.html
{% extends "user/index.html" %} {% load crispy_forms_tags %} {% block start %}

<div class="row align-items-center justify-content-center">
  <div class="col-md-8 col-md-offset-2">
    {% if not user.is_authenticated %}
    <center>
      <form
        method="POST"
        style="
          border: 1px solid black;
          margin: 4%;
          padding: 10%;
          border-radius: 1%;
        "
      >
        {% csrf_token %}
        <fieldset class="form-group">{{ form | crispy}}</fieldset>
        <br />
        <center>
          <button
            type="submit"
            class="btn btn-dark"
          >
          <span class="glyphicon glyphicon-log-in"></span>Login
          </button>
        </center>
        <br />
        <sub style="text-align: left"
          ><a
            href="{% url 'users:register' %}"
            style="
              text-decoration: none;
              color: blue;
              padding: 2%;
              cursor: pointer;
              margin-right: 2%;
            "
            >don't have account,sign up</a
          >
          <a
            href="{% url 'users:password-reset' %}"
            style="
              text-decoration: none;
              color: blue;
              padding: 2%;
              cursor: pointer;
              margin-right: 2%;
            "
            >Forgot your password?</a
          >
        </sub>
      </form>
    </center>
    {% else %}
    <div class="panel-group">
      <div class="panel panel-warning">
        <div class="panel-body">
          You are already logged in. You should not be here
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %} {% endblock start %}

user/templates/user/password_reset_complete.html
{% extends "user/base.html" %} {% block content %}
<div class="container my-3 p-3">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="div shadow-lg border-0 rounded-lg mt-0 mb-3">
        <div class="alert alert-info text-center">
          Your new password has been set. You may go ahead and
          <a href="{% url 'users:login' %}">login here</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

user/templates/user/password_reset_email.html
{% autoescape off %} 
You are receiving this email as you have request for a password reset. To reset password for your Check Out Account, click the link below: 

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %} 

If clicking the link doesn't work, please copy and paste the URL in a new browser window instead. 

Sincerely, 
Check Out Team 
{% endautoescape %}

user/templates/user/register.html
{% extends "user/index.html" %}
{% load crispy_forms_tags %}
{% block start %}

<div class="content-section col-md-8 col-md-offset-2" style="margin: 0 auto">
{% if not verify_code %}
<form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
	{% csrf_token %}
	<fieldset class="form-group">
	{{ form | crispy }}
	</fieldset>
	<br />
	<center>
	<button style="background: black; padding:2%; font-size: 1rem; color:white;" class="btn btn-outline-info" name='signup' type="submit"><span class="glyphicon glyphicon-check"></span>  sign up</button>
	</center>
	<br />
	<sub><a href="{% url "users:login" %}" style="text-decoration: none; color: blue; padding:3%; cursor:pointer;">Already have an account? Sign in</a></sub>
</form>
{% else %}
{% if email_send_failed %}
<div class="panel panel-danger">
	<div class="panel-heading">Email send failed, try again later.</div>
</div>
{% else %}
{% if validate_failed %}
<div class="panel-group">
	<div class="panel panel-danger">
		<div class="panel-heading">{{error_text}}</div>
	</div>
</div>
{% endif %}
<form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
	{% csrf_token %}
	<div class="form-group">
		<label for="exampleInputEmail1">A verification code has been sent to your email</label>
		<input type="Text" class="form-control" id="code" name="code" aria-describedby="Verification Code" placeholder="Verification Code">
	</div>
	<button type="submit" name="verify" class="btn btn-primary">Submit</button>
</form>
{% endif %}
{% endif %}
</div>
{% endblock start %}