BookClub/urls.py
from django.urls import path
from .views import (
    create_book_club,
    edit_book_club,
    book_club_details,
    error_page,
    voting_form,
    delete_book_club,
    deletion_confirmation,
)
from django.contrib.auth.decorators import login_required

# app_name = "bookclub"

urlpatterns = [
    path("error", error_page, name="error_page"),
    path("create", login_required(create_book_club), name="create-book-club"),
    path("delete", login_required(delete_book_club), name="delete_book_club"),
    path("delete/confirmation", deletion_confirmation, name="deletion_confirmation"),
    path("<slug:slug>", book_club_details, name="details"),
    path("<int:book_club_id>/edit", edit_book_club, name="edit_book_club"),
    path("voting/<slug:slug>", voting_form, name="voting"),
]

CheckOut/CheckOut/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_view
from django.contrib.auth import views as auth

app_name = 'checkout'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
	path('logout/', auth.LogoutView.as_view(template_name ='user/index.html'), name ='logout'),
    path('libraries/', include('libraries.urls')),

]

CheckOut/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth

app_name = "checkout"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("user.urls")),
    path(
        "logout/",
        auth.LogoutView.as_view(template_name="user/index.html"),
        name="logout",
    ),
    path("libraries/", include("libraries.urls")),
    path("bookclub/", include("BookClub.urls")),
    path("notifications/", include("Notifications.urls")),
    path("books/", include("books.urls")),
    path("chat/", include("chat.urls")),
]

chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
    path("name/<str:roomname>/", views.name, name="name"),
]

BookClub/forms.py
from django import forms
from django.forms import ModelForm
from .models import BookClub
from user.models import CustomUser
from django.core.exceptions import ValidationError
from Notifications.models import TransferOwnershipNotif


class BookClubVotingForm(forms.Form):
    book1 = forms.CharField(label="book1", max_length=200)
    book2 = forms.CharField(label="book2", max_length=200)
    book3 = forms.CharField(label="book3", max_length=200)


class BookClubForm(ModelForm):
    class Meta:
        model = BookClub
        fields = (
            "name",
            "description",
            "currentBook",
            "currentAuthor",
            "currentBookIsbn",
            "meetingDay",
            "meetingStartTime",
            "meetingEndTime",
            "meetingOccurence",
        )
        labels = {
            "currentBook": "Current Book",
            "currentAuthor": "Current Author",
            "currentBookIsbn": "Current Book ISBN",
            "meetingStartTime": "Meeting Start Time",
            "meetingEndTime": "Meeting End Time",
            "meetingDay": "Meeting Day",
        }
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(
                attrs={"class": "form-control", "cols": 50, "rows": 3}
            ),
            "currentBook": forms.TextInput(attrs={"class": "form-control"}),
            "currentAuthor": forms.TextInput(attrs={"class": "form-control"}),
            "currentBookIsbn": forms.TextInput(attrs={"class": "form-control"}),
            "meetingDay": forms.Select(attrs={"class": "form-control"}),
            "meetingOccurence": forms.Select(attrs={"class": "form-control"}),
            "libraryId": forms.Select(attrs={"class": "form-control"}),
            "admin": forms.Select(attrs={"class": "form-control"}),
        }

    def __init__(self, *args, **kwargs):
        super(BookClubForm, self).__init__(*args, **kwargs)
        self.fields["meetingDay"].required = True
        self.fields["meetingOccurence"].required = True
        self.fields["meetingStartTime"].widget = forms.TimeInput(
            format="%I:%M %p", attrs={"class": "form-control", "type": "time"}
        )
        self.fields["meetingEndTime"].widget = forms.TimeInput(
            format="%I:%M %p", attrs={"class": "form-control", "type": "time"}
        )

    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get("meetingStartTime")
        end_time = cleaned_data.get("meetingEndTime")

        if start_time and end_time and end_time <= start_time:
            raise ValidationError(
                "Meeting end time must be after the meeting start time."
            )

        return cleaned_data


class BookClubEditForm(ModelForm):
    new_admin = forms.ModelChoiceField(
        label="New Admin",
        queryset=CustomUser.objects.all(),
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    class Meta:
        model = BookClub
        fields = [
            "name",
            "description",
            "currentBook",
            "currentAuthor",
            "currentBookIsbn",
            "meetingDay",
            "meetingStartTime",
            "meetingEndTime",
            "meetingOccurence",
            "libraryId",
        ]

        exclude = ["admin"]

        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(
                attrs={"class": "form-control", "cols": 50, "rows": 3}
            ),
            "currentBook": forms.TextInput(attrs={"class": "form-control"}),
            "currentAuthor": forms.TextInput(attrs={"class": "form-control"}),
            "currentBookIsbn": forms.TextInput(attrs={"class": "form-control"}),
            "meetingDay": forms.Select(attrs={"class": "form-control"}),
            "meetingStartTime": forms.TimeInput(
                attrs={"class": "form-control", "type": "time"}
            ),
            "meetingEndTime": forms.TimeInput(
                attrs={"class": "form-control", "type": "time"}
            ),
            "meetingOccurence": forms.Select(attrs={"class": "form-control"}),
            "libraryId": forms.Select(attrs={"class": "form-control"}),
            # "new_admin": forms.Select(attrs={"class": "form-control"}),
        }
        labels = {
            "name": "Name",
            "description": "Description",
            "currentBook": "Current book pick",
            "currentAuthor": "Current pick's author",
            "currentBookIsbn": "Current pick's ISBN",
            "meetingDay": "Meeting day",
            "meetingStartTime": "Meeting Start Time",
            "meetingEndTime": "Meeting End Time",
            "meetingOccurence": "Meeting Frequency",
            "libraryId": "Library",
        }

    def clean_new_admin(self):
        # each book club should only have one pending request
        new_admin = self.cleaned_data["new_admin"]
        pending_req = TransferOwnershipNotif.objects.filter(
            book_club=self.instance, status="pending"
        )
        error_message = (
            "You have already made a transfer admin request."
            + "Please wait for the previous request to be declined to make a new one."
        )
        if pending_req:
            raise ValidationError(error_message)
        return new_admin

BookClub/views.py
from django.shortcuts import render, redirect, get_object_or_404
from libraries.models import Library
from BookClub.models import BookClub, VotingPoll, PollChoice
from Notifications.models import TransferOwnershipNotif, BookClubUpdatesNotif
from books.models import Book
from django.contrib import messages
from .forms import BookClubForm, BookClubEditForm, BookClubVotingForm
from django.conf import settings
from django.core.mail import send_mail
from smtplib import SMTPException
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.db.models import Q
from books.utils import get_book_cover


def voting_form(request, slug):
    bc = BookClub.objects.get(id=slug)
    context = {}
    if bc.polls != 0:
        poll = VotingPoll.objects.get(id=bc.polls)
        choices = poll.choices.all()
        context = {
            "previous_form": True,
            "who_voted": poll.who_voted.all(),
            "choice1": {"name": choices[0].name, "votes": choices[0].votes},
            "choice2": {"name": choices[1].name, "votes": choices[1].votes},
            "choice3": {"name": choices[2].name, "votes": choices[2].votes},
        }
    if request.method == "POST":
        if "submit" in request.POST:
            form = BookClubVotingForm(request.POST)
            if form.is_valid():
                bc = BookClub.objects.get(id=slug)
                poll = VotingPoll.objects.create(
                    poll_set=True, name="Voting Poll for " + bc.name
                )
                ch1 = PollChoice.objects.create(
                    name=form.cleaned_data["book1"], votes=0
                )
                ch1.save()
                poll.choices.add(ch1)
                ch2 = PollChoice.objects.create(
                    name=form.cleaned_data["book2"], votes=0
                )
                ch2.save()
                poll.choices.add(ch2)
                ch3 = PollChoice.objects.create(
                    name=form.cleaned_data["book3"], votes=0
                )
                ch3.save()
                poll.choices.add(ch3)
                if bc.polls != 0:
                    VotingPoll.objects.filter(id=bc.polls).delete()
                poll.save()
                bc.polls = poll.id
                bc.save()
                return redirect("details", slug=slug)
    return render(request, "voting.html", context)


def checkIfAllowedToSubscribe(bookclub, request):
    if bookclub.libraryId.NYU == "0" or (
        bookclub.libraryId.NYU == "1" and request.user.status == "nyu"
    ):
        bookclub.members.add(request.user)
    else:
        messages.error(
            request, "You must be a NYU student to subscribe to this book club"
        )


def getBookInfo(currentBook, currentAuthor, currentBookIsbn):
    book_list = Book.objects.filter(
        Q(title__icontains=currentBook) | Q(isbn__exact=currentBookIsbn)
    )

    if len(book_list) == 0:
        book = Book.objects.create(
            title=currentBook, author=currentAuthor, isbn=currentBookIsbn
        )
        return book
    else:
        return book_list[0]


def book_club_details(request, slug):
    bc = BookClub.objects.get(id=slug)
    book = getBookInfo(bc.currentBook, bc.currentAuthor, bc.currentBookIsbn)
    book_cover = get_book_cover(book)
    average = book.average_rating
    poll = None
    if bc.polls != 0:
        poll = VotingPoll.objects.get(id=bc.polls)
    context = {
        "bookclub": bc,
        "member_count": bc.members.all().count(),
        "subscribed": bc.members.contains(request.user)
        if request.user.is_authenticated
        else False,
        "voting_poll": poll,
        "choices": poll.choices.all() if poll else None,
        "amount_voted": poll.get_all_votes() if poll else None,
        "voted": poll.did_vote(request.user) if poll else None,
        "is_member": True if request.user in bc.members.all() else False,
        "book": book,
        "book_cover": book_cover,
        "average_rating": average,
    }
    if request.method == "POST":
        if "subscribe" in request.POST:
            checkIfAllowedToSubscribe(bc, request)
            return redirect("details", slug=slug)
        elif "unsubscribe" in request.POST:
            if poll and poll.did_vote(request.user):
                poll.remove_user_from_poll(request.user)
            bc.members.remove(request.user)
            return redirect("details", slug=slug)
        elif "choice1" in request.POST:
            selected_choice = poll.choices.all()[0]
            selected_choice.votes += 1
            selected_choice.user_voted.add(request.user)
            selected_choice.save()
            poll.who_voted.add(request.user)
            return redirect("details", slug=slug)
        elif "choice2" in request.POST:
            selected_choice = poll.choices.all()[1]
            selected_choice.votes += 1
            selected_choice.user_voted.add(request.user)
            selected_choice.save()
            poll.who_voted.add(request.user)
            return redirect("details", slug=slug)
        elif "choice3" in request.POST:
            selected_choice = poll.choices.all()[2]
            selected_choice.votes += 1
            selected_choice.user_voted.add(request.user)
            selected_choice.save()
            poll.who_voted.add(request.user)
            return redirect("details", slug=slug)
    return render(request, "details.html", context)


@login_required
def create_book_club(request):
    library_id = request.GET.get("libraryId") or request.POST.get("libraryId")
    library = Library.objects.get(id=int(library_id))
    form = BookClubForm(request.POST or None)
    if request.method == "POST":
        if request.user.status == "nyu" and library.NYU == "1":
            if form.is_valid():
                book_club = form.save(commit=False)
                book_club.admin = request.user
                book_club.libraryId = library
                book_club.save()
                book_club.members.add(request.user)

                return redirect("details", slug=book_club.id)
        elif request.user.status != "nyu" and library.NYU == "1":
            return redirect("error_page")

        else:
            if form.is_valid():
                library = Library.objects.get(id=int(library_id))
                book_club = form.save(commit=False)
                book_club.admin = request.user
                book_club.libraryId = library
                book_club.save()
                book_club.members.add(request.user)
                return redirect("details", slug=book_club.id)
    else:
        form = BookClubForm()
    return render(request, "bookclub.html", {"form": form})


def get_email_content(fields_changed, bc_name):
    # input is dict of fields and data changed by form
    # if name is changed, take old name as bc_name
    content = "Here are the latest updates from " + bc_name + "\n\r"
    notif = ""
    index = 0
    list_bullet = "{index}.\t{bc_name}"
    result = "{new_data}. \n"
    notif_r = "{new_data}--!!--"
    for k, v in fields_changed.items():
        index += 1
        if k == "currentAuthor" or k == "currentBookIsbn":
            continue
        if k == "name":
            new_line = " changed its name to "
        elif k == "description":
            new_line = " updated its description - "
        elif k == "currentBook":
            new_line = " is currently reading "
        elif k == "meetingDay":
            new_line = " changed its meeting day to "
        elif k == "meetingStartTime":
            new_line = " updated its meeting time to start from "
        elif k == "meetingEndTime":
            new_line = " updated its meeting time to end at "
        elif k == "meetingOccurence":
            new_line = " updated its meeting occurrence to "
        elif k == "libraryId":
            new_line = " is now associated with "
        elif k == "currentBook":
            new_line = " updated its current book pick to "
        else:
            new_line = " has a new admin: "
        notif += bc_name + new_line + notif_r.format(new_data=v)
        content += (
            list_bullet.format(index=index, bc_name=bc_name)
            + new_line
            + result.format(new_data=v)
        )
    return content, notif


def edit_book_club(request, book_club_id):
    book_club = get_object_or_404(BookClub, id=book_club_id)
    original_bc_name = book_club.name

    if request.user != book_club.admin:
        return redirect("error_page")

    if request.method == "POST":
        form = BookClubEditForm(request.POST, instance=book_club)
        if not form.has_changed():
            form = BookClubEditForm(instance=book_club)
            messages.error(request, "Please modify the fields before saving!")
            return render(
                request, "bookclub_edit.html", {"form": form, "book_club": book_club}
            )
        if form.is_valid():
            if "new_admin" in request.POST:
                new_admin = form.cleaned_data["new_admin"]
                if new_admin != book_club.admin:
                    transferReq = TransferOwnershipNotif(
                        original_owner=request.user,
                        new_owner=new_admin,
                        book_club=book_club,
                        status="pending",
                        date_created=datetime.now(),
                    )
                    transferReq.save()
            form.save()
            fields_changed = form.changed_data
            changed_fields_and_data = {}
            for i in fields_changed:
                if i == "new_admin":
                    continue
                changed_fields_and_data[i] = request.POST[i]
            if changed_fields_and_data:
                try:
                    content, notif = get_email_content(
                        changed_fields_and_data, original_bc_name
                    )

BookClub/templates/bookclub.html
{% extends "user/base.html" %}
{% block title%}Create Book Club{% endblock%}
{% block content %}
<body>
<div class="container p-3">
    <div class="row align-items-center vh-100">
        <div class="col-8 mx-auto">
            <div class="card shadow border">
                <div class="card-body d-flex flex-column align-self-center">
                    <h3 class="card-title">Create Book Club</h3>
                    <form action="" method="POST">
                      {% csrf_token %} 
                      {{ form.as_p }}
                      <div class="text-center">
                        <input type = "submit" value ="Submit" class = "btn btn-dark" >
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

BookClub/templates/bookclub_deletion.html
{% extends "user/base.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Club Deleted</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card text-center">
                    <div class="card-header">
                        <h1>Book Club Deletion</h1>
                    </div>
                    <div class="card-body">
                        <p class="card-text">The book club has been successfully deleted.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

BookClub/templates/bookclub_detail.html
{% extends "user/base.html" %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="./cards.css" type="text/css"/>
    {% load bootstrap5 %} {% bootstrap_css %} {%
    bootstrap_javascript %} {% load bootstrap_icons %}
    <title>{{ book_club.name }} Details</title>
</head>
{% block content %}
<body>
    <!-- Display Book Cover -->
    <!-- {% if book_cover %}
        <img src="{{ book_cover }}" alt="Book Cover">
    {% else %}
        <p>Book cover not available</p>
    {% endif %} -->
    <h1>{{ book_club.name }} Details</h1>
    <p>Description: {{ book_club.description }}</p>
    <p>Current Book: {{ book_club.currentBook }}</p>
    <p>Meeting Day: {{ book_club.meetingDay }}</p>
    <p>Meeting Start Time: {{ book_club.meetingStartTime }}</p>
    <p>Meeting End Time: {{ book_club.meetingEndTime }}</p>
    <p>Admin: {{book_club.admin}}</p>

    <label for="members">Members:</label>
        {% for member in book_club.members.all %}
            <div class="col-sm-8">
                {{ member.username }}
            </div>
        {% endfor %}

    {% if request.user == book_club.admin %}
        <a href="{% url 'edit_book_club' book_club.id %}" class="btn btn-primary">Edit Book Club</a>
    {% endif %}
</body>
{% endblock %}
</html>

BookClub/templates/bookclub_edit.html
{% extends "user/base.html" %}
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="./cards.css" type="text/css" />
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %} {% load
    bootstrap_icons %} 
    <title>Edit Book Club</title>

</head>
{% block content %}
{% if messages %}
    {% for message in messages %}
    <div class="container-fluid p-0">
      <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
    {% endfor %}
{% endif %}
<body>
  <div class="container p-3">
    <div class="row align-items-center vh-100">
        <div class="col-8 mx-auto">
            <div class="card shadow border">
                <div class="card-body d-flex flex-column align-self-center">
                    <h3 class="card-title">Edit Book Club: {{ book_club.name }}</h3>
                    <form method="POST">
                      {% csrf_token %} 
                      {% for field in form %}
                            <p>{{ field.label_tag }} {{ field }}
                              {% if field.errors %}<li class="alert alert-danger">{{ field.errors|striptags }}</li> {% endif %}
                            </p>
                      {% endfor %}
                
                      <label for="members">Members:</label>
                      {% for member in book_club.members.all %}
                      <div class="col-sm-8">{{ member.username }}</div>
                      {% endfor %}
                      <div class="text-center">
                      <button type="submit" class="btn btn-primary" {% if request.user != book_club.admin %}disabled{% endif %}>Save Changes</button>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
  </body>
  {% endblock %}
</html>

BookClub/templates/bookclub_error_page.html
{% extends "user/base.html" %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card text-center">
                <div class="card-header">
                    <h1>Book Club Deletion</h1>
                </div>
                <div class="card-body">
                    <p class="card-text">The book club has been successfully deleted.</p>
                    <a href="{% url 'home' %}" class="btn btn-primary">Return to Home</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

BookClub/templates/details.html
{% extends "user/base.html" %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
		{% load bootstrap5 %} {% bootstrap_css %}
	</head>
	{% block content %}
	<body>
		{% if messages %}
		{% for message in messages %}
			<div class="container-fluid p-0">
				<div class="alert alert-danger alert-dismissible fade show" role="alert" >
					{{ message }}
					<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				</div>
			</div>
		{% endfor %}
		{% endif %}
		<div class='container'>
			{% if bookclub %}
			<div class='container'>
				<div class='row justify-content-center'>
					<center><h1>{{bookclub.name}}</h1></center>
				</div>
				<div class='row justify-content-center'>
					<center>
					<p>{{bookclub.description}}</p>
					<p>Current Book Reading: {{bookclub.currentBook}}</p>
					{% if book_cover %}
						<img src="{{ book_cover }}" alt="Book Cover">
					{% else %}
						<p>Book cover not available</p>
					{% endif %}
					<p>Average rating: {{ average_rating }}</p>

					{% if user.is_authenticated %}
						<form method="post" action="{% url 'rate_book' pk=book.id %}">
							{% csrf_token %}
							<h3>Rate this book:</h3>
							
							<div class="rating">
								<style>
									.rating {
										display: inline-block;
										unicode-bidi: bidi-override;
										direction: rtl;
									}
									.rating input {
										display: none;
									}
									.rating label {
										position: relative;
										display: inline-block;
										font-size: 25px;
										color: #ffcc00;
										cursor: pointer;
										margin-right: 5px;
									}
									.rating label:before {
										content: "\2605";
										/* position: absolute; */
									}
									.rating label:hover:before,
									.rating label:hover ~ label:before {
										content: "\2605";
										color: #ff9900;
									}
									.rating input:checked ~ label {
										content: "\2605";
										color: #ff9900;
									}
									.checked {
										color: #ff9900;
									}
									form {
										margin-bottom: 20px;
									}
								</style>
								{% for i in "54321" %}
									<input class="rating" type="radio" id="star{{ i }}" name="rating" value="{{ i }}">
									<label class="rating" for="star{{ i }}"></label>
								{% endfor %}
							</div>
					
							<button type="submit" class="btn btn-light">Submit Rating</button>
						</form>
					{% endif %}

					<p>Meeting Time: {{bookclub.meetingDay}} , {{bookclub.meetingStartTime}} - {{bookclub.meetingEndTime}}</p>
					<p>Current number of Members: {{member_count}}</p>
					</center>
				</div>
			</div>
			<div class='container' style='margin-bottom:10px'>
				<div class='row justify-content-center'>
					<center>
						<form method="POST">
							{% csrf_token %}
							{% if user.is_authenticated %}
								<button onclick="location.href='{% url 'chat:name' roomname=bookclub.name %}'" type="button" class="btn btn-primary">Chat Room</button>
								{% if bookclub.admin != user %}
									{% if subscribed %}
										<button type="submit" name="unsubscribe" class="btn btn-primary">Unsubscribe</button>
									{% else %}
										<button type="submit" name="subscribe" class="btn btn-primary">Subscribe</button>
									{% endif %}
								{% endif %}
								{% if bookclub.admin == user%}
								<button onclick="location.href='{% url 'edit_book_club' bookclub.id %}'" type="button" class="btn btn-primary">Edit</button>
								<button onclick="location.href='{% url 'voting' bookclub.id %}'" type="button" class="btn btn-primary">Voting Form</button>
								{% endif %}
							{% endif %}
							</form>
						{% if bookclub.admin == user %}
							<form action="{% url 'delete_book_club' %}" method="post" style="display: inline-block;">
								{% csrf_token %}
								<input type="hidden" name="book_club_id" value="{{ bookclub.id }}">
								<button type="submit" class="btn btn-danger">Delete</button>
							</form>
						{% endif %}
					</center>
				</div>
			</div>
			{% if voting_poll and is_member %}
			<div class='container' style='margin-bottom:10px'>
				<div class='row justify-content-center'>
					<center>
						<h2>Choose the next book you like to read at this book club</h2>
						<p>Members voted: {{amount_voted}}/{{member_count}}</p>
						{% if not voted %}
						<form method="POST">
							{% csrf_token %}
							{% for choice in choices %}
								<button type="submit" name='choice{{ forloop.counter }}' class="btn btn-secondary" >{{choice.name}}</button>
							{% endfor %}
						</form>
						{% else %}
						<p>You already voted.</p>
						{% endif %}
					</center>
				</div>
			</div>
			{% endif %}
			{% else %}
			<div class='container'>
				<center><h1>The Book Club you are trying to reach is either does not exist or you have no permission to view</h1></center>
			</div>
			{% endif %}
		</div>
	</body>
	{% endblock %}
</html>

BookClub/templates/voting.html
{% extends "user/base.html" %}
<!DOCTYPE html>
<html>
	<head>
	</head>
	{% block content %}
	<body>
		<div class='container'>
			<center>
				<h1>Create Next Book Poll</h1>
				<p>What book would you want the club to vote on for the next read?</p>
				<form method="POST">
					{% csrf_token %}
					<label >Book 1 </label>
					<input id="book1" type="text" name="book1">
					<label >Book 2 </label>
					<input id="book2" type="text" name="book2">
					<label >Book 3 </label>
					<input id="book3" type="text" name="book3">
					<button class="btn btn-primary" type="submit" name="submit">Submit</button>
				</form>
				{% if previous_form %}
					<h2>Previous Form:</h2>
					<p><u><b>Who Voted: </b></u></p>
					{% for user in who_voted %}
						<p>{{user.username}}</p>
					{% endfor %}
					<p><u><b>Choices:</b></u></p>
					<p>{{choice1.name}}: {{choice1.votes}}</p>
					<p>{{choice2.name}}: {{choice2.votes}}</p>
					<p>{{choice3.name}}: {{choice3.votes}}</p>
				{% endif %}
			</center>
		</div>
	</body>
	{% endblock	%}
</html>