CheckOut/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth

app_name = "checkout"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("user.urls")),
    path(
        "logout/",
        auth.LogoutView.as_view(template_name="user/index.html"),
        name="logout",
    ),
    path("libraries/", include("libraries.urls")),
    path("bookclub/", include("BookClub.urls")),
    path("notifications/", include("Notifications.urls")),
    path("books/", include("books.urls")),
    path("chat/", include("chat.urls")),
]

chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
    path("name/<str:roomname>/", views.name, name="name"),
]

libraries/urls.py
from django.urls import path
from libraries.views import LibraryView, LibraryListView

app_name = "libraries"
urlpatterns = [
    path("<int:pk>", LibraryView.as_view(), name="library-detail"),
    path("", LibraryListView.as_view(), name="library-list"),
]

login/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.login, name="login"),
]

user/urls.py
from django.urls import path, reverse_lazy
from . import views
from .views import ChangePasswordView, ResetPasswordView
from django.contrib.auth import views as auth_views

app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.user_login, name="login"),
    path("register", views.register, name="register"),
    path("profile", views.user_profile, name="user_profile"),
    path("unsubscribe/<slug:slug>/", views.unsubscribe, name="unsubscribe"),
    path("mute/<slug:slug>/", views.mute, name="mute"),
    path("password-change/", ChangePasswordView.as_view(), name="password_change"),
    path(
        "password-reset/",
        ResetPasswordView.as_view(),
        {
            "post_reset_redirect": "users:password_reset_complete",
        },
        name="password-reset",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="user/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="user/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

CheckOut/login/models.py
from django.db import models

# Create your models here.

CheckOut/user/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# class UserProfile(models.Model):

#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     bio = models.TextField()

#     def __str__(self):
#         return self.user.username

#     def get_absolute_url(self):
#         return reverse("_detail", kwargs={"pk": self.pk})

user/models.py
import re
from django.db import models
from django.contrib.auth.models import AbstractUser
from Notifications.models import Notification
from django.db.models import Q


class CustomUser(AbstractUser):
    STATUS = (
        ("reader", "Reader"),
        ("librarian", "Librarian"),
        ("nyu", "NYU Associated"),
    )

    username = models.CharField(max_length=50, blank=True, null=True, unique=True)
    email = models.EmailField(max_length=254, unique=True)
    first_name = models.CharField(max_length=50, blank=True, null=True, unique=False)
    last_name = models.CharField(max_length=50, blank=True, null=True, unique=False)
    status = models.CharField(max_length=100, choices=STATUS, default="reader")

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = [
        "email",
    ]

    def get_unread_notifications(self):
        unread_notifications = Notification.objects.filter(
            Q(
                transferownershipnotif__new_owner=self.id,
                transferownershipnotif__status="pending",
                is_read=False,
            )
            | Q(
                transferownershipnotif__original_owner=self.id,
                transferownershipnotif__status="declined",
                is_read=False,
            )
            | Q(bookclubupdatesnotif__receiving_user=self.id, is_read=False)
        ).count()

        return unread_notifications

    def get_user_status(email):
        domain = re.search(r"@[\w.]+", email).group()
        if domain == "@nyu.edu":
            return "nyu"
        else:
            return "reader"

    def save(self, *args, **kwargs):
        self.status = CustomUser.get_user_status(self.email)
        super(CustomUser, self).save(*args, **kwargs)

    def __str__(self):
        return self.username

CheckOut/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import validate_email
from django.core.validators import RegexValidator
# from .models import UserProfile

class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={'placeholder': 'First Name','class': 'form-control'}))
    last_name = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={'placeholder': 'Last Name','class': 'form-control'}))
    username = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={'placeholder': 'Username','class': 'form-control'}))
    email = forms.EmailField(required=True, label='Email', widget=forms.TextInput(attrs={'placeholder': 'email','class': 'form-control'}))
    password1 = forms.CharField(max_length=20, required=True, label='Password', widget=forms.PasswordInput(attrs={'placeholder': 'Password','class': 'form-control'}))
    password2 = forms.CharField(max_length=20, required=True, label='Confirm Password', widget=forms.PasswordInput(attrs={'placeholder': 'Re-enter Password','class': 'form-control'}))
    
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']
    
    def clean_email(self):  
        email = self.cleaned_data['email'].lower()  
        new = User.objects.filter(email=email)  
        #if new.count():
        #    raise forms.ValidationError("Email Already Exist")  
        #if not validate_email(email):
        #    raise forms.ValidationError("Incorrect email format!") 
        return email  
        
    def clean_password1(self):
        password = self.cleaned_data.get("password1")
        if password.isnumeric():
            raise forms.ValidationError("Password cannot only contain numbers")
        elif password.isalpha():
            raise forms.ValidationError("Password cannot only contain characters")
        else:
            return password

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(required=True) # TODO: send confirmation email to change?

    class Meta:
        model = User
        fields = ['username', 'email']			

class ValidateForm(forms.Form):
	alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')
	code = forms.CharField(max_length=10, validators=[alphanumeric])
	
	def clean_code(self):
		code = self.cleaned_data.get('code')
		if code.isalnum():
			return code
		raise forms.ValidationError("Code can only be alphanumeric")

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator
from validate_email import validate_email
from .models import CustomUser


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "First Name", "class": "form-control"}
        ),
    )
    last_name = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Last Name", "class": "form-control"}
        ),
    )
    username = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Username", "class": "form-control"}
        ),
    )
    email = forms.EmailField(
        required=True,
        label="Email",
        widget=forms.TextInput(attrs={"placeholder": "email", "class": "form-control"}),
    )
    password1 = forms.CharField(
        max_length=20,
        required=True,
        label="Password",
        widget=forms.PasswordInput(
            attrs={"placeholder": "Password", "class": "form-control"}
        ),
    )
    password2 = forms.CharField(
        max_length=20,
        required=True,
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={"placeholder": "Re-enter Password", "class": "form-control"}
        ),
    )

    class Meta:
        model = CustomUser
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
        ]

    def clean_email(self):
        email = self.cleaned_data["email"].lower()
        new = CustomUser.objects.filter(email=email)
        if new.count():
            raise forms.ValidationError(
                "Email already exists! Please use another email."
            )
        is_valid = validate_email(email)
        if not is_valid:
            raise forms.ValidationError("Incorrect email format!")
        return email

    def clean_password1(self):
        password = self.cleaned_data.get("password1")
        if password.isnumeric():
            raise forms.ValidationError("Password cannot only contain numbers")
        elif password.isalpha():
            raise forms.ValidationError("Password cannot only contain characters")
        else:
            return password


class UpdateUserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UpdateUserForm, self).__init__(*args, **kwargs)
        try:
            self.fields["email"].initial = self.instance.email
        except CustomUser.DoesNotExist:
            pass

    username = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Username", "class": "form-control"}
        ),
    )

    first_name = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "First Name", "class": "form-control"}
        ),
    )
    last_name = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Last Name", "class": "form-control"}
        ),
    )

    email = forms.EmailField(
        required=True,
        label="Email",
        widget=forms.TextInput(attrs={"placeholder": "email", "class": "form-control"}),
    )

    class Meta:
        model = CustomUser
        fields = ["username", "first_name", "last_name", "email"]

    def clean_email(self):
        email = self.cleaned_data["email"].lower()
        new = CustomUser.objects.filter(email=email)
        if email != self.instance.email and new.count():
            raise forms.ValidationError(
                "Email already exists! Please use another email."
            )
        is_valid = validate_email(email)
        if not is_valid:
            raise forms.ValidationError("Incorrect email format!")
        return email


class ValidateForm(forms.Form):
    alphanumeric = RegexValidator(
        r"^[0-9a-zA-Z]*$", "Only alphanumeric characters are allowed."
    )
    code = forms.CharField(max_length=10, validators=[alphanumeric])

    def clean_code(self):
        code = self.cleaned_data.get("code")
        if code.isalnum():
            return code
        raise forms.ValidationError("Code can only be alphanumeric")

CheckOut/login/views.py
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.template import loader

# Create your views here.


def login(request):
	template = loader.get_template('login/login.html')
	context = {}
	return HttpResponse(template.render(context, request))
    
	

CheckOut/user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from .forms import UserRegisterForm, ValidateForm
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
from django.urls import reverse_lazy
from smtplib import SMTP, SMTPException
import time
import random,string

from .forms import UserRegisterForm, UpdateUserForm
from django.views import View

    
def index(request):
	return render(request, 'user/index.html', {'title':'index'})

def register(request):
	if request.method == 'POST':
		if 'signup' in request.POST:
			form = UserRegisterForm(request.POST)
			request.session['register_form'] = request.POST
			if form.is_valid():
				vcode = ''.join(random.choices(string.ascii_letters, k=5))
				email = form.cleaned_data.get('email');
				print(f'vcode: {vcode}')
				request.session['verification_code'] = { 'code': vcode , 'ttl' : (time.time() + 300)}
				subject, from_email,message = 'Verify Your Email', 'test@gmail.com', f'This is your verification code: {vcode}'
				try:
					send_mail(subject,message,from_email,[email],fail_silently = False,)
					context = {
						'form' : form,
						'title' : 'validate code',
						'verify_code': True,
					}
					return render(request,'user/register.html',context)
				except SMTPException as e:
					print(e)
					context = {
						'form' : form,
						'title' : 'validate code',
						'verify_code': True,
						'email_send_failed' : True
					}
					return render(request,'user/register.html',context)
		elif 'verify' in request.POST:
			print('Verify stuff')
			validate_form = ValidateForm(request.POST)
			print(request.POST)
			if validate_form.is_valid():
				code = validate_form.cleaned_data.get('code')
				validation_token = request.session.get('verification_code')
				print(f'{validation_token}\n Time Now: {time.time()}')
				if validation_token and validation_token['ttl'] > time.time():
					if code == validation_token['code'] :
						post_req = request.session.pop('register_form')
						form = UserRegisterForm(post_req)
						form.save()
						username = form.cleaned_data.get('username')
						email = form.cleaned_data.get('email')
						password = form.cleaned_data.get('password1')
							
						user = authenticate(username=username,password=password)
						login(request,user)
						messages.success(request, f'Your account has been created ! You are now able to log in')
						del request.session['verification_code']
						return redirect('users:index')
					else:
						context = {
							'title' : 'validate code',
							'verify_code': True,
							'validate_failed': True,
							'error_text': 'Incorrect Validation Code, make sure you entered in the right code.'
						}
						return render(request,'user/register.html',context)
				else:
					context = {
							'title' : 'validate code',
							'verify_code': True,
							'validate_failed': True,
							'error_text': 'The verification code has expired.'
					}
					return render(request,'user/register.html',context)
			else:
				print("Failed validation")
			
	else:
		form = UserRegisterForm()
	return render(request, 'user/register.html', {'form': form, 'title':'register here'})

def Login(request):
	if request.method == 'POST':

		# TODO: use AuthenticationForm

		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username = username, password = password)
		if user is not None:
			form = login(request, user)
			messages.success(request, f' welcome {user.username} !!')
			return redirect('users:index')
		else:
			messages.info(request, f'account does not exist plz sign in')
	form = AuthenticationForm()
	return render(request, 'user/login.html', {'form':form, 'title':'log in'})

@login_required
def user_profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users:user_profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        
    return render(request, 'user/profile.html', {'user_form': user_form})

class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'user/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('users:index')

login/views.py
from django.http import HttpResponse
from django.template import loader

# Create your views here.


def login(request):
    template = loader.get_template("login/login.html")
    context = {}
    return HttpResponse(template.render(context, request))

CheckOut/user/templates/user/change_password.html
{% extends "user/index.html" %} {% load crispy_forms_tags %} {% block start %}
<div class="form-content my-3 p-3">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-5">
        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
          <div class="card-header justify-content-center">
            <h3 class="font-weight-light my-4 text-center">
              Change Your Password
            </h3>
          </div>
          {% if form.errors %}
          <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
              {% for key, value in form.errors.items %}
              <strong>{{ value }}</strong>
              {% endfor %}
            </div>
            <button
              type="button"
              class="close"
              data-dismiss="alert"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %}

          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              <div class="form-row">
                <div class="col-md-10 offset-md-1">
                  <div class="form-group">
                    <label class="small mb-1" for="id_old_password"
                      >Old Password</label
                    >
                    <input
                      type="password"
                      name="old_password"
                      autocomplete="new-password"
                      class="form-control"
                      required
                      id="id_old_password"
                      placeholder="Enter Old Password"
                    />
                    <span> </span>
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-md-10 offset-md-1">
                  <div class="form-group">
                    <label class="small mb-1" for="id_new_password1"
                      >New Password</label
                    >
                    <input
                      type="password"
                      name="new_password1"
                      autocomplete="new-password"
                      class="form-control"
                      required
                      id="id_new_password1"
                      placeholder="Enter New Password"
                    />
                    <span> </span>
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-md-10 offset-md-1">
                  <div class="form-group">
                    <label class="small mb-1" for="id_new_password2"
                      >New Password Confirmation</label
                    >
                    <input
                      type="password"
                      name="new_password2"
                      autocomplete="new-password"
                      required
                      id="id_new_password2"
                      class="form-control"
                      placeholder="Confirm New Password"
                    />
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-md-10 offset-md-1">
                  <div class="form-group mt-0 mb-1">
                    <button
                      type="submit"
                      class="col-md-12 btn btn-dark"
                      id="reset"
                    >
                      Update Password
                    </button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock start %}

CheckOut/user/templates/user/email.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title></title>
		<style>
			@import url('https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900');
		</style>
	</head>
	<body style="background: #f5f8fa;font-family: 'Roboto', sans-serif;">
		<div style="width: 90%;max-width:600px;margin: 20px auto;background: #ffffff;">
			<section style="margin: 0 15px;color:#425b76;">
				<h2 style="margin: 40px 0 27px 0;text-align: center;">Thank you to registration</h2>
				<hr style="border:0;border-top: 1px solid rgba(66,91,118,0.3);max-width: 50%">
				<p style="font-size:15.5px;font-weight: bold;margin:40px 20px 15px 20px;">Hi {{username}}, we have received your details and will process soon.</p>
			</section>
		</div>
	</body>
</html>

CheckOut/user/templates/user/index.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="title" content="project">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="language" content="English">

<title>{{title}}</title>

<!-- bootstrap file -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- bootstrap file-->

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<!-- main css -->
<link rel="stylesheet" type="text/css" href="{% static "index.css" %}" />


<!-- message here -->

{% if messages %}
{% for message in messages %}

<script>
	alert("{{ message }}");
</script>

{% endfor %}
{% endif %}


</head>

<body class="container-fluid">


<header class="row">

	<!-- navbar-->
	<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
		<button class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" class="styleheader" href="{% url "users:index" %}">Check Out</a>
		</div>
		<div class="collapse navbar-collapse" id="mainNavBar">
		<ul class="nav navbar-nav navbar-right">
			<li><a href="{% url "users:index" %}">Home</a></li>

			{% if user.is_authenticated %}
			<li><a href="{% url "logout" %}"><span class="glyphicon glyphicon-log-out"></span>  Logout</a></li>
			<li><a href="{% url "users:user_profile" %}"><span class="glyphicon glyphicon-log-out"></span>  User Profile</a></li>
			{% else %}
			<li><a href="{% url "users:register" %}"><span class="glyphicon glyphicon-user"></span>  Sign up</a></li>
			<li><a href="{% url "users:login" %}"><span class="glyphicon glyphicon-log-in"></span>  Log in</a></li>
			{% endif %}

		</ul>
		</div>
	</div>
	</nav>
</header>
<br/>
<br>
<br>
<div class="row">
	{% block start %}
	{% if user.is_authenticated %}
	<center><h1>Welcome back {{user.first_name}}!</h1></center>
	{% else %}
	<center><h1>Check Out</h1></center>
	{% endif %}
	<div>
		<center><button type="button" class="btn btn-info"><a href="{% url "libraries:index"%}">View Libraries</a></button></center>
	</div>
	{% endblock %}
</div>
</body>

</html>

CheckOut/user/templates/user/login.html
{% extends "user/index.html" %}
{% load crispy_forms_tags %}
{% block start %}

<div class="content-section col-md-8 col-md-offset-2">
{% if not user.is_authenticated %}
<center>
<form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
	{% csrf_token %}
	<fieldset class="form-group">
	{{ form | crispy}}
	</fieldset>
<center>
	<button style="background: black; font-size: 2rem; padding:1%;" class="btn btn-outline-info" type="submit"><span class="glyphicon glyphicon-log-in"></span>  login</button>
</center>
<br/>
<sub style="text-align: left;"><a href="{% url 'users:register' %}" style="text-decoration: none; color: blue; padding:2%; cursor:pointer; margin-right:2%;">don't have account,sign up</a></sub>
</form>
</center>
{% else %}
<div class="panel-group">
  <div class="panel panel-warning">
    <div class="panel-body">You are already logged in. You should not be here</div>
  </div>
</div>
</div>
{% endif %}
{% endblock start %}

CheckOut/user/templates/user/profile.html
{% extends "user/index.html" %} {% load crispy_forms_tags %} {% block start %}
{% if user_form.errors %}
<div class="alert alert-danger alert-dismissible" role="alert">
  <div id="form_errors">
    {% for key, value in user_form.errors.items %}
    <strong>{{ value }}</strong>
    {% endfor %}
  </div>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}
<div class="form-content">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
      <div class="col-md-5">
        <div class="form-group">
          <label class="small mb-1">Username:</label>
          {{ user_form.username }}
          <label class="small mb-1">Email:</label>
          {{ user_form.email }}
        </div>
        <div class="form-group">
          <a href="{% url "users:password_change" %}">Change Password</a>
        </div>
      </div>
    </div>
    <br /><br />
    <button type="submit" class="btn btn-dark btn-lg">Save Changes</button>
    <button type="reset" class="btn btn-dark btn-lg">Reset</button>
  </form>
</div>
{% endblock start %}

CheckOut/user/templates/user/register.html
{% extends "user/index.html" %}
{% load crispy_forms_tags %}
{% block start %}

<div class="content-section col-md-8 col-md-offset-2">
{% if not verify_code %}
<form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
	{% csrf_token %}
	<fieldset class="form-group">
	{{ form | crispy }}
	</fieldset>
	<center>
	<button style="background: black; padding:2%; font-size: 2rem; color:white;" class="btn btn-outline-info" name='signup' type="submit"><span class="glyphicon glyphicon-check"></span>  sign up</button>
	</center>
	<br />
	<sub><a href="{% url "users:login" %}" style="text-decoration: none; color: blue; padding:3%; cursor:pointer;">Already have an account ?</a></sub>
</form>
{% else %}
{% if email_send_failed %}
<div class="panel panel-danger">
	<div class="panel-heading">Email send failed, try again later.</div>
</div>
{% else %}
{% if validate_failed %}
<div class="panel-group">
	<div class="panel panel-danger">
		<div class="panel-heading">{{error_text}}</div>
	</div>
</div>
{% endif %}
<form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
	{% csrf_token %}
	<div class="form-group">
		<label for="exampleInputEmail1">A verification code has been sent to your email</label>
		<input type="Text" class="form-control" id="code" name="code" aria-describedby="Verification Code" placeholder="Verification Code">
	</div>
	<button type="submit" name="verify" class="btn btn-primary">Submit</button>
</form>
{% endif %}
{% endif %}
</div>
{% endblock start %}