CheckOut/CheckOut/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_view
from django.contrib.auth import views as auth

app_name = 'checkout'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
	path('logout/', auth.LogoutView.as_view(template_name ='user/index.html'), name ='logout'),
    path('libraries/', include('libraries.urls')),

]

CheckOut/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth

app_name = "checkout"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("user.urls")),
    path(
        "logout/",
        auth.LogoutView.as_view(template_name="user/index.html"),
        name="logout",
    ),
    path("libraries/", include("libraries.urls")),
    path("bookclub/", include("BookClub.urls")),
    path("notifications/", include("Notifications.urls")),
    path("books/", include("books.urls")),
    path("chat/", include("chat.urls")),
]

Notifications/urls.py
from django.urls import path
from Notifications.views import NotificationListView

app_name = "notifications"

urlpatterns = [path("", NotificationListView.as_view(), name="notifications")]

chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
    path("name/<str:roomname>/", views.name, name="name"),
]

user/urls.py
from django.urls import path, reverse_lazy
from . import views
from .views import ChangePasswordView, ResetPasswordView
from django.contrib.auth import views as auth_views

app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.user_login, name="login"),
    path("register", views.register, name="register"),
    path("profile", views.user_profile, name="user_profile"),
    path("unsubscribe/<slug:slug>/", views.unsubscribe, name="unsubscribe"),
    path("mute/<slug:slug>/", views.mute, name="mute"),
    path("password-change/", ChangePasswordView.as_view(), name="password_change"),
    path(
        "password-reset/",
        ResetPasswordView.as_view(),
        {
            "post_reset_redirect": "users:password_reset_complete",
        },
        name="password-reset",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="user/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="user/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

Notifications/models.py
from django.db import models


# Create your models here.
class Notification(models.Model):
    is_read = models.BooleanField(default=False)
    safe_to_delete = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    # receiving_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    class Meta:
        # abstract = True
        ordering = ["-date_created"]


class TransferOwnershipNotif(Notification):
    original_owner = models.ForeignKey(
        "user.CustomUser", on_delete=models.CASCADE, related_name="old_admin"
    )
    new_owner = models.ForeignKey(
        "user.CustomUser", on_delete=models.CASCADE, related_name="new_admin"
    )
    book_club = models.ForeignKey(
        "BookClub.BookClub",
        on_delete=models.CASCADE,
        related_name="transferred_book_club",
    )
    status_types = ["accepted", "pending", "declined"]
    status = models.CharField(status_types, max_length=30)


class BookClubUpdatesNotif(Notification):
    def fields_changed_to_list(self):
        result = self.fields_changed.split("--!!--")
        if len(result) == 1:
            return result
        return result[:-1]

    receiving_user = models.ForeignKey(
        "user.CustomUser", on_delete=models.CASCADE, related_name="receiving_user"
    )
    book_club = models.ForeignKey(
        "BookClub.BookClub", on_delete=models.CASCADE, related_name="updated_book_club"
    )
    fields_changed = models.TextField()

Notifications/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from django.views import View
from django.db.models import Q
from .models import Notification
from Notifications.models import TransferOwnershipNotif, BookClubUpdatesNotif
from datetime import datetime


# Create your views here.
class NotificationListView(View):
    model = Notification

    def get(self, request):
        if request.user.is_anonymous:
            return render(request, "Notifications/error_page.html")
        object_list = Notification.objects.filter(
            Q(
                transferownershipnotif__new_owner=self.request.user,
                transferownershipnotif__status="pending",
            )
            | Q(
                transferownershipnotif__original_owner=self.request.user,
                transferownershipnotif__status="declined",
            )
            | Q(bookclubupdatesnotif__receiving_user=self.request.user)
        )

        for n in object_list:
            n.is_read = True
            n.save()
        return render(
            request, "Notifications/notifications.html", {"notifs": object_list}
        )

    def post(self, request, *args, **kwargs):
        notif_type = request.POST.get("notif_type")
        if notif_type == "transfer":
            req_status = request.POST.get("status")
            transferRequestNotif = TransferOwnershipNotif.objects.get(
                id=request.POST["id"]
            )
            if req_status:
                if req_status == "Accept":
                    new_owner = transferRequestNotif.new_owner
                    book_club = transferRequestNotif.book_club
                    if new_owner not in book_club.members.all():
                        book_club.members.add(new_owner)
                    book_club.admin = new_owner
                    book_club.save()
                    transferRequestNotif.status = "accepted"
                    bc_members = book_club.members.all()
                    message = (
                        book_club.name
                        + " has a new admin: "
                        + book_club.admin.first_name
                    )
                    for mem in bc_members:
                        if not book_club.silenceNotification.contains(mem):
                            updateNotif = BookClubUpdatesNotif(
                                safe_to_delete=True,
                                date_created=datetime.now(),
                                receiving_user=mem,
                                book_club=book_club,
                                fields_changed=message,
                            )
                            updateNotif.save()
                else:
                    transferRequestNotif.status = "declined"
                    transferRequestNotif.is_read = False
                transferRequestNotif.safe_to_delete = True
                transferRequestNotif.save()
            else:
                transferRequestNotif.delete()
        else:
            print(request.POST)
            updateNotif = BookClubUpdatesNotif.objects.get(id=request.POST["id"])
            updateNotif.delete()
        return HttpResponseRedirect("#")

Notifications/templates/Notifications/error_page.html
{% extends "user/base.html" %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card text-center">
                <div class="card-body">
                    <p class="card-text">You do not have permissions to visit this page! Please sign in first.</p>
                    <a href="{% url 'users:index' %}" class="btn btn-dark">Return to Home</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

Notifications/templates/Notifications/notifications.html
{% extends "user/base.html" %} 
<!DOCTYPE html>

<html>
  <head>
    <title>{% block title %}Notifications{% endblock %}</title>
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %} {% load bootstrap_icons %}
  </head>
{% block content %}
{% if messages %}
    {% for message in messages %}
    <div class="container-fluid p-0">
      <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
    {% endfor %}
{% endif %}
<div class="container p-3">
    <div class="row justify-content-center">
    <h4 class="text-center"> Notifications </h4>
    {% for notif in notifs %}
        <div class="card m-2" style="width: 60rem;">
            <div class="card-body">
            {% if notif.transferownershipnotif %}
                <div class="row">
                    <div class="col-md-8">
                    <h6 class="card-title">Admin Transfer Request</h6>
                    </div>
                    {% if notif.transferownershipnotif.safe_to_delete %}
                    <div class="col-md-4">
                            <div class="float-end">
                                <form method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="notif_type" value='transfer'>
                                    <input type="hidden" name="id" value={{ notif.transferownershipnotif.id }}>
                                    <input class="btn btn-close" type="submit" name="delete" value ='' aria-label="Close">
                                </form>    
                            </div>
                        </div>
                    {% endif %}
                </div>
                {% if notif.transferownershipnotif.new_owner == request.user and notif.transferownershipnotif.status == 'pending' %}
                    <div class="row">
                        <div class="col-md-8">
                            <p class="card-text">{{ notif.transferownershipnotif.original_owner}} wants to transfer the ownership of {{ notif.transferownershipnotif.book_club }} to you</p>
                        </div>
                        <div class="col-md-4">
                            <div class="float-end">
                                <form method="post">
                                    {% csrf_token %}
                                    <input class="btn btn-outline-success btn-md" type="submit" value="Accept" name="status">
                                    <input class="btn btn-outline-danger btn-md" type="submit" value="Decline" name="status">
                                    <input type="hidden" name="notif_type" value='transfer'>
                                    <input type="hidden" name="id" value={{ notif.transferownershipnotif.id }}>
                                </form>
                            </div>
                        </div>
                    </div>
                {% elif notif.transferownershipnotif.original_owner == request.user and notif.transferownershipnotif.status == 'declined'%}
                    <p class="card-text">{{notif.transferownershipnotif.new_owner}} has declined your request to take ownership of {{notif.transferownershipnotif.book_club}}. </p>
                {% endif %}
            {% elif notif.bookclubupdatesnotif %}
                <div class="row">
                    <div class="col-md-8">
                    <h6 class="card-title">Updates from {{notif.bookclubupdatesnotif.book_club}}</h6>
                    </div>
                    <div class="col-md-4">
                        <div class="float-end">
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="notif_type" value='update'>
                                <input type="hidden" name="id" value={{ notif.bookclubupdatesnotif.id }}>
                                <input class="btn btn-close" type="submit" name="delete" value ='' aria-label="Close">
                            </form>    
                        </div>
                    </div>
                </div>
                <p style="font-size:15px">The following details have been updated for {{ notif.bookclubupdatesnotif.book_club }}:</p>
                <ol>
                    {% for f in notif.bookclubupdatesnotif.fields_changed_to_list %}
                    <li style="font-size:14px">{{f}}</li>
                    {% endfor %}
                </ol>
                <a href="{% url 'details' notif.bookclubupdatesnotif.book_club.id %}" style="font-size:14px">Click to view more details</a>
            {% endif %}
            </div>
        </div>
    {% empty %}
    <center>
        <p>There are no notifications to view.</p>
    </center>
    {% endfor %}
</div>
<div>
{% endblock content %}
</html>